apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.service.name }}
    namespace: {{ .Values.service.namespace }}
    annotations:
        {{- range $key, $value := .Values.service.annotations }}
            {{ $key }}: {{ $value | quote }}
        {{- end}}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.externalPort }}
          targetPort: {{ .Values.service.internalPort }}
          protocol: {{ .Values.service.protocol }}
    selector:
        app: {{ .Values.service.selector.app }}
